### ISSUE TITLE
\andothersdelimの挙動

### ISSUE THREAD

**Issue by imaru** [sbtseiji/biblatex-jpa#5]
jpa.cbxの65行目による \andotherdelim の挙動がおかしいように思います。現状のまま
\renewcommand*{\andothersdelim}{\space{et al.,}\space}%
だと、\textciteで引用したときにもカンマが付加されてしまいます。

日本語文献との関係から考えると
\renewcommand*{\andothersdelim}{\space{et al.}\space}%
とすべきかと思い試すと、これだと\parencite{}のときにカンマが付与されません。

65行目をコメントアウトするとfitst authorの姓にカンマが付与されるので、65行目はet al.にしておくのがいいと思ったのですが、なぜカンマが付与されないのかを追いかけることができていません。

問題の報告だけで申し訳ありません。

**Comment by sbtseiji** [comment]
ありがとうございます。

たしかに，このままだと\textciteのときも Smith et al., (2024) のようになってしまいますね。見落としていました。

対処法としては， \andothersdelim からコンマをなくし，文脈に応じてコンマを付加するようにするか，\andothersdelim はそのままにして，\textcite用に\andothersdelimnocomma のようなコンマ抜きの別のマクロを作成するかということになると思います。多分，後者の方が全体に影響しにくいと思いますが，あとでスクリプトを見直して，対処しておきます。

**Comment by sbtseiji** [comment]
\cite，\parenciteと\textciteで\andothersdelimの定義を別にしました。
